
# Use new container infrastructure to enable caching
sudo: false


# Do not choose a language; we provide our own build tools.
language: elm

node_js:
  - 12
install:

# Build dependencies
- npm install
- npm link

script:
# Build the package, its tests, and its docs and run the tests
- elm-boil init my-elm-app
- cd my-elm-app
- npm run build
- npm start &
